### ISSUE TITLE
letters connecting issues?

### ISSUE THREAD

**Issue by Gue3bara** [alif-type/mada#10]
<img width="88" alt="screen shot 2016-06-21 at 4 26 07 am" src="https://cloud.githubusercontent.com/assets/12478169/16216205/204d7760-3769-11e6-9e02-e99709e9e734.png">
and i think the issue is with the anchor on U-FEF2 & U-FEF0

**Comment by khaledhosny** [comment]
This is by design, one can change this with ss01 feature.
![a](https://cloud.githubusercontent.com/assets/93914/16252039/b9eb578c-3833-11e6-93ef-4b121b3cefba.png)

**Comment by davelab6** [comment]
What does ss01 look like?

**Comment by khaledhosny** [comment]
There is an image in my comment above.

**Comment by Gue3bara** [comment]
@khaledhosny i honestly don't understand what you meant here

**Comment by khaledhosny** [comment]
The raised part of the final ي is intentional not a bug, to get a not raised final ي you need to enable `ss01` font feature.
