### ISSUE TITLE
Overlap issuse

### ISSUE THREAD

**Issue by alexeiva** [alif-type/mada#11]
Hi Khaled, 

There is an overlap issue in Latin Cap 'A'

<img width="536" alt="screen shot 2016-06-28 at 19 51 12" src="https://cloud.githubusercontent.com/assets/16634089/16436183/be58983a-3d69-11e6-853d-4827f133f6e8.png">
<img width="545" alt="screen shot 2016-06-28 at 19 51 04" src="https://cloud.githubusercontent.com/assets/16634089/16436185/bfbc8254-3d69-11e6-8e23-49350890fc0c.png">

**Comment by khaledhosny** [comment]
This is already fixed in the repository, Google fonts is using a slightly old version.

**Comment by khaledhosny** [comment]
BTW, this does not happen for me on Linux, even with Google fonts version.

**Comment by alexeiva** [comment]
Oh, okay. Sorry then!

**Comment by andreapaiola** [comment]
In Mac OS X with google webfont is visible

![schermata 2016-07-20 alle 11 18 15](https://cloud.githubusercontent.com/assets/16450997/16981794/8ec3f538-4e6c-11e6-8aa1-d8f798792b74.png)

**Comment by andreapaiola** [comment]
![schermata 2016-07-20 alle 11 28 53](https://cloud.githubusercontent.com/assets/16450997/16981897/36929ea4-4e6d-11e6-8cdf-7467ec31cfe5.png)

**Comment by khaledhosny** [comment]
This has been fixed here, google fonts still needs to update its copy. See google/fonts#326 and google/fonts#287.

**Comment by andreapaiola** [comment]
How can we ask to update?

**Comment by davelab6** [comment]
Khaled has asked me and it is in my queue.

**Comment by andreapaiola** [comment]
no news?

**Comment by andreapaiola** [comment]
I have downloaded the google fonts and I have loaded like this
https://google-webfonts-helper.herokuapp.com/fonts/mada?subsets=latin,arabic

Please, how can I update with this repo files?

**Comment by khaledhosny** [comment]
The OTF and TTF files are available from [releases section](https://github.com/khaledhosny/mada/releases), you will have to generate WOFF and WOFF2 files yourself.

**Comment by andreapaiola** [comment]
Thank you, what do you use to generate WOFF and WOFF2 ?

**Comment by khaledhosny** [comment]
I use [sfnt2woff](https://people.mozilla.org/~jkew/woff/) and [woff2_compress](https://github.com/google/woff2).
