### ISSUE TITLE
Designspace file is out-dated

### ISSUE THREAD

**Issue by behdad** [alif-type/mada#12]
It lists Medium as a master, whereas in reality Regular is a master.

**Comment by khaledhosny** [comment]
Yes. But Regular is just renamed Medium to make @davelab6 happy until I can interpolate the missing weights. I still have interpolation issues that I didn’t have time to figure out.

**Comment by behdad** [comment]
`fontmake -m` builds the missing weights.  Though, you need to weight a couple weeks for us to implement GPOS interpolation.

**Comment by khaledhosny** [comment]
I can do the interpolation already, but I have few master incompatibility issues that are resulting in broken interpolated glyphs. I started working on them now.
