### ISSUE TITLE
Arabic letters (Meem and Khah)

### ISSUE THREAD

**Issue by t4rik** [alif-type/mada#15]
## Arabic letters issues (Meem and Khah)

OS: Ubuntu (Linux/Unix-like)
App: File Manager
Font version: 1.3
Font type: TTF
Font size: 10px

Meem: meem end show like meem begin.
Khah: khah dot continue (Show like a line)

Mada font
![screenshot from 2016-07-31 01-35-26](https://cloud.githubusercontent.com/assets/7073523/17273956/baaedc1e-56c1-11e6-8108-e7e625c14857.png)

Segoe UI font (same conditions)
![screenshot from 2016-07-31 01-59-13](https://cloud.githubusercontent.com/assets/7073523/17273996/ee80954a-56c2-11e6-9c51-69f04bcc8f0c.png)

**Comment by khaledhosny** [comment]
- Meem shape is by design.
- Khah dot issue is strange, what is the operating system/application used, and are you using the TTF or OTF files?

**Comment by t4rik** [comment]
TTF and I put images.

**Comment by khaledhosny** [comment]
Can you try the OTF files? The name of the operating system and its version are important for finding the possible source of the problem.

**Comment by t4rik** [comment]
Example: (مدخل إلى عالم الخُطوط)
Mada font (v 1.3 / OTF) - same conditions
![screenshot from 2016-07-31 19-02-35](https://cloud.githubusercontent.com/assets/7073523/17278328/bcf98f82-5752-11e6-8477-1c2c0cb1a03e.png)

Arial font - same conditions
![screenshot from 2016-07-31 19-03-50](https://cloud.githubusercontent.com/assets/7073523/17278337/fbde3a4a-5752-11e6-8df6-6930df9c88e1.png)

Conclusion: Dot Khah is very weak for small size (10 px)

**Comment by khaledhosny** [comment]
Are you using, Linux, Windows or MacOS? Where are you using the font, in a web page or other application?

**Comment by t4rik** [comment]
Linux, file manager.

**Comment by t4rik** [comment]
Another example in LibreOffice (OS: Linux)
ex: ( قبل أن ندخل إلى عالم الخُطوط، خوخ فاكهة. )
![screenshot from 2016-07-31 19-52-05](https://cloud.githubusercontent.com/assets/7073523/17278609/d2c38592-5758-11e6-8cc5-b9fe091c18c7.png)

**Comment by khaledhosny** [comment]
This looks ugly, can you try enabling font hinting?

**Comment by t4rik** [comment]
I found 4 options: None, Slight, Medium & Full.
Default: Slight.

**Comment by khaledhosny** [comment]
See if Medium or Full make any difference.

**Comment by t4rik** [comment]
Yes, Medium good choice for Mada Arabic letters.
![screenshot from 2016-08-01 01-15-42](https://cloud.githubusercontent.com/assets/7073523/17280459/6e9a91e8-5788-11e6-996d-d388ac7e2b10.png)

Hinting Full and None working too.

**Comment by khaledhosny** [comment]
OK, so I think you will need to enable medium hinting for this font, if you don’t want to change the hinting settings for other fonts then you can use FontConfig to set the hinting of this font only.

**Comment by t4rik** [comment]
How to set hinting Meda font only?
