### ISSUE TITLE
Strange rendering of the 'A' in all caps 900 weight

### ISSUE THREAD

**Issue by ahimsauzi** [alif-type/mada#17]
Hello,

Thanks for a beautiful font! I just want to make sure this is not intentional but the all caps A character is rendering with some artifact when using as web font. Inside Photoshop, font renders as expected. The issue is most noticeable in the 900 weight in all cups. Please attached.

![screen shot 2016-09-28 at 10 34 23 am](https://cloud.githubusercontent.com/assets/253339/18925103/64bf3e32-8567-11e6-9be5-1aceffe2b197.png)

Thank you.

**Comment by khaledhosny** [comment]
See https://github.com/khaledhosny/mada/issues/11.
