### ISSUE TITLE
Broken diacritics

### ISSUE THREAD

**Issue by chichilatte** [alif-type/mada#25]
Love this font but it seems like it's screwing up certain diacritics. Here's an example in Google Docs...

<img src="https://i.imgur.com/sXwqHIP.png">

And how it should look (using Verdana here)...

<img src="https://i.imgur.com/lYsRUhF.png">

The problem is the little diagonal accent called a `kasra`, utf16 char `\u0650`. I'm not sure if other accents also have problems.

---
Here's the selectable text if that's any help...
# الرِّياضَة

Also: Looking around, i get the same problem in Google Fonts and Adobe AIR. In LibreOffice the kasra doesn't show at all.

**Comment by chichilatte** [comment]
How would one go about fixing this i wonder, e.g. what software, good arabic accent info, etc.?

**Comment by khaledhosny** [comment]
The positioning is by design; I subscribe to the school that places the kasra under the base character regardless of the presence or absence of shadda. If this can help you, it shouldn’t be hard to have a stylistic set font feature that enables alternate placement.

**Comment by chichilatte** [comment]
Ahh ok, that's interesting. Our translator (based in Syria) thought it was a rendering error. I'll get back to her with your comment. Are there any other similar accent choices you've made in the font, do you think?

It would be great if the kasra under the shadda could be added, thank you, but I'm not sure if stylistic sets are supported on the platform we're developing for (Adobe AIR). I suspect they're not, googling comes up empty :( 

Maybe an alternative font family (seems like overkill!)?

**Comment by khaledhosny** [comment]
The same happens with kasratan (double kasra). I can add the stylistic set and you can use a tool like [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze) to create an alternate font family with the stylistic set being the default.

**Comment by chichilatte** [comment]
Wow Khaled you are amazing. Please do add the stylistic set, really appreciated.

**Comment by khaledhosny** [comment]
Please test and let me know if you have any issues.

**Comment by chichilatte** [comment]
Yes! Black is old, blue is new...
<img src="https://i.imgur.com/pP65uwK.png">

Note for anyone doing something similar: Here's what I had to do in the terminal to get pyftfeatfreeze to work:
```
cd /path/to/your/pyftfeatfreeze/folder
chmod gou+x pyftfeatfreeze.py
sudo pip install fonttools
./pyftfeatfreeze.py -f 'ss03' -S -U SS03 YourMadaFolder/Mada-Regular.otf YourMadaFolder/Mada-RegularSS03.otf
```
(I added the S and U switches to add "SS03" to the font name, just so i could compare the old and new versions easily)

Thanks again Khaled!
