### ISSUE TITLE
Why is final yeh disconnected by default?

### ISSUE THREAD

**Issue by davelab6** [alif-type/mada#26]
Repeating #10 and #24, I spoke with Gaber about this, and neither of us understand why the default is not a smooth connection with the baseline, while ss01 is designed to be smooth and connecting. 

Could you explain why you prefer having the default and ss01 designs this way, and if you would consider inverting them? :)

**Comment by khaledhosny** [comment]
Because I like it this way? 😄

Final yeh often has a raised “bridge” in various Arabic writing styles, and this “disconnection” simulate that without making the shape too complex for this design. I like it that way and think the smooth connection is too bland.

I can be convinced to switch the default if many people are complaining.

**Comment by khaledhosny** [comment]
On the practical side, it helps making the descender of the final yeh align with other descenders without making it uncomfortably shallow.

**Comment by davelab6** [comment]
@Gue3bara thoughts?

**Comment by Gue3bara** [comment]
@davelab6 @khaledhosny I can see your point of trying to raise the yeh bridge or make it visible without raising it up too high but i think users will think that the glyph is just broken. 
a broken baseline is what i see specially that this "disconnection" was not done in any other glyphs to make it feel usual across the font design. 
I personally would recommend the switch

**Comment by davelab6** [comment]
@khaledhosny thoughts? :)

**Comment by khaledhosny** [comment]
Still not convinced, I really like how it looks currently 🙂. Let me think about it when I’m about to cut the next release.

**Comment by khaledhosny** [comment]
Not going to change my mind on this.
