### ISSUE TITLE
Make Faa more like a Faa than Qaaf

### ISSUE THREAD

**Issue by SafaAlfulaij** [alif-type/mada#28]
![screenshot_ _](https://user-images.githubusercontent.com/3509617/34638569-3f936e80-f2df-11e7-92f1-4582723da723.png)
Its more like غوغل درايڨ thank غوغل درايڤ, or I think I just got that to my eye.

**Comment by khaledhosny** [comment]
![](https://user-images.githubusercontent.com/93914/34639419-b0c23dbc-f2e8-11e7-82f6-458bb6c9b4e9.png)
