### ISSUE TITLE
TTFs

### ISSUE THREAD

**Issue by davelab6** [alif-type/mada#3]
Please provide TTFs :)

**Comment by khaledhosny** [comment]
The release now has TTF version (I did not add the files under version control to not bloat the repo any further).

**Comment by davelab6** [comment]
I agree that is best

**Comment by davelab6** [comment]
The OTF files are still in the repo, and not in the release. Should they be removed from the repo and added to the release zip?

**Comment by khaledhosny** [comment]
They are on the release zip (in the root directory), I just checked. I’m keeping them in the repo because I don’t trust the reproducibility of my current toolchain.

**Comment by davelab6** [comment]
Ah yes sorry, I was looking at Reem's release
