### ISSUE TITLE
some italic fonts not working

### ISSUE THREAD

**Issue by squareclouds** [alif-type/mada#30]
hello,
the following files are not working properly somehow:

- extra light italic
- light italic
- italic

neither macOS nor fontexplorer X (latest versions of both) seem to be able to preview nor install them.

and google fonts does not provide italics at all? :-/

thanks in advance, looking forward to some insight about this

**Comment by khaledhosny** [comment]
Font Book should give some clue why it can’t install the fonts.

**Comment by squareclouds** [comment]
hello,

here is the output when i check one of those files

![grafik](https://user-images.githubusercontent.com/9073054/51519873-71e40100-1e22-11e9-997e-e8e16f931cb2.png)

showing error on "system check"

on macOS Mojave 10.14.2

**Comment by khaledhosny** [comment]
Sorry, I don’t know what to do with this. Apple command line font tools (need to be downloaded from https://developer.apple.com/fonts/) should be able to give more useful errors, but my macOS system is broken and I can’t check it myself.

**Comment by squareclouds** [comment]
sadly i cannot install on mojave, it is not compatible (tool is from 2011). i just looked for alternatives but didnt find anything useful. 

will be using a replacement font for italics in documents and force italic on the browser.

i hope someone with an onlder macOS version can help with this
