### ISSUE TITLE
Self-intersecting glyphs

### ISSUE THREAD

**Issue by dscorbett** [alif-type/mada#33]
Some glyphs intersect themselves in such a way that, at least in Chrome and Firefox, the overlaps appear white. Examples include U+0041 LATIN CAPITAL LETTER A, U+0472 CYRILLIC CAPITAL LETTER FITA, and U+0030 DIGIT ZERO with 'ss05'. Not all self-intersecting glyphs have this problem.

**Comment by khaledhosny** [comment]
Are you testing released version or master branch? Files in master might not be very usable at the moment.

**Comment by dscorbett** [comment]
This is from the master branch.
