### ISSUE TITLE
Duplication of Regular font by different names: Mada.otf and Mada-Regular.otf

### ISSUE THREAD

**Issue by munzirtaha** [alif-type/mada#36]
Two fonts are available with Regular style, one needs to be removed

**Comment by khaledhosny** [comment]
Mada.otf is a [variable font](https://web.dev/variable-fonts/), the other files are static instances of specific styles.

**Comment by khaledhosny** [comment]
If you are packaging/installing the font, either use Mada.otf or the other files, but not both. The variable font should work as usual in most applications, and applications that directly support variable fonts might provide extra control to adjust font axes.

Some applications don’t support variable fonts correctly, though, like LibreOffice and in this case the static instances would be more appropriate.

**Comment by munzirtaha** [comment]
Ah! I should have noticed. However, I suggest that you rename it to MadaVariable.otf Mada-VF.otf like you did with your other ReemKufi-VF.otf so it's clearer. I also suggest that you not only rename the file but the font itself so that both can be packaged together which allow users to choose their preferable format based on the application support.

I tested Mada.otf in LibreOffice and it shows all the styles and it seems to work properly so I wonder why you mentioned LibreOffice doesn't support variable fonts correctly. Of course, nothing advanced like "adjust axes" but it works.

I also noticed that MS bahnschrift.ttf variable font shows on Scribus though one style only but yours doesn't. What's the reason for this?

Thanks!

**Comment by khaledhosny** [comment]
> Ah! I should have noticed. However, I suggest that you rename it to MadaVariable.otf Mada-VF.otf like you did with your other ReemKufi-VF.otf so it's clearer. I also suggest that you not only rename the file but the font itself so that both can be packaged together which allow users to choose their preferable format based on the application support.

I instead dropped the VF suffix from ReemKufi; it is a technical jargon that users should not worry about. I should add a note in the README, though.

> I tested Mada.otf in LibreOffice and it shows all the styles and it seems to work properly so I wonder why you mentioned LibreOffice doesn't support variable fonts correctly. Of course, nothing advanced like "adjust axes" but it works.

Try exporting to PDF or printing.

> I also noticed that MS bahnschrift.ttf variable font shows on Scribus though one style only but yours doesn't. What's the reason for this?

The TTF variable fonts are backward-compatible, an application that has no idea about variable fonts will get the default instance as if it were a regular TTF font. OTF variable fonts, in the other hand, use a new glyph outlines table (`CFF2` instead of the old `CFF` table), so applications that don’t know about the new table will not know what to do with this font (LibreOffice suffers from a similar issue in PDF export only, TTF variable will export to the default instance regardless of the weight you used, and OTF variable will show blank glyphs).

**Comment by munzirtaha** [comment]
> I instead dropped the VF suffix from ReemKufi;

huh! I shouldn't have reminded you ;)
Currently most companies are using that to make it easier to have both formats and this would help in testing till applications support them properly.

Among many others: Adobe made SourceSansVariable, SourceSerifVariable and SourceCodeVariable
29LT made 29LT Bukra Variable and 29LT Baseet Variable ...

But I agree with you, that it should be removed in the future.

Thanks for the clarification, it's now clear.

**Comment by khaledhosny** [comment]
File name alone would not be enough, I’ll need to change the family and probably other name entries too.
