### ISSUE TITLE
Addition of Arabic Presentation Forms

### ISSUE THREAD

**Issue by ethanl13** [alif-type/mada#39]
Would it be possible to add the characters from Arabic Presentation Forms-B (https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B) and the applicable characters from Arabic Presentation Forms-A (https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-A)?

Example from Arial Unicode MS
![image](https://user-images.githubusercontent.com/106971651/172162191-62ad20ac-9bc8-488b-9129-ffce2fd82025.png)

**Comment by khaledhosny** [comment]
Presentation forms are legacy and obsolete mechanism of handling Arabic, why do you want them?

**Comment by ethanl13** [comment]
Hello, I have just sent you an email.
