### ISSUE TITLE
Minor things

### ISSUE THREAD

**Issue by davelab6** [alif-type/mada#9]
Thin

Technical Problems: Points are sometimes missing at extrema

Design Mistakes: uni00AD ( this glyph is not meant to contain a shape or have a width ), /Euro (shape seems to be a mistaken interpolation or something.) having /guillemotleft/guillemotright but not /guilsinglleft/guilsinglright seems odd, brokenbar (the gap is too small), /underscore (this should no have gaps - the opposite in fact - it should overlap itself when set)

Suggestions for improvement: yen ( stokes closer together than is ideal now - move them apart), /asciicircum (a little taller please), please include /ellipsis/bullet/emdash/endash

Medium

as above but also - Euro missing

Black

as above but also - Euro missing

**Comment by khaledhosny** [comment]
> uni00AD ( this glyph is not meant to contain a shape or have a width )

Huh? Soft hyphen has a shape and width in almost all fonts on my system.

> /Euro (shape seems to be a mistaken interpolation or something.)

I don’t see what is wrong with the Euro.

> having /guillemotleft/guillemotright but not /guilsinglleft/guilsinglright seems odd

There is guilsinglleft and guilsinglright.

> brokenbar (the gap is too small), /underscore (this should no have gaps - the opposite in fact - it should overlap itself when set), Suggestions for improvement: yen ( stokes closer together than is ideal now - move them apart), /asciicircum (a little taller please).

That is subjective, but this is how Source Sans Pro is designed and I’d like to keep it that way. I don’t usually change the Latin designs unless it is required to work better with the Arabic.

> please include /ellipsis/bullet/emdash/endash

They are included.

> Medium
> 
> as above but also - Euro missing
> 
> Black
> 
> as above but also - Euro missing

Both fonts have a Euro glyph.

**Comment by khaledhosny** [comment]
> Technical Problems: Points are sometimes missing at extrema

I don’t think this is a big deal, never knew what is wrong with not having points at extrema to be honest.

**Comment by davelab6** [comment]
Was from a 3rd party reviewer :)
